In [13]:
import pandas as pd
import json
import csv
import pydantic 
from pydantic import BaseModel, Field
from typing import List, Optional

In [14]:
with open("results.json", "r") as f:
    data = json.load(f)
    df = pd.DataFrame(data)

In [15]:
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class LogoImage(BaseModel):
    id: str
    size: int
    filetype: str
    originalname: str
    path: str


class Platform(BaseModel):
    thehub: bool
    plusimpact: bool


class RecommendedBy(BaseModel):
    name: Optional[str] = None
    website: Optional[str] = None


class SlackNotifications(BaseModel):
    jobCreated: bool
    jobEnded: bool
    applicationCreated: bool
    applicationCommented: bool


class Location(BaseModel):
    address: str
    locality: str
    route: str
    postalCode: str
    country: str


class Center(BaseModel):
    type: str
    _id: str
    coordinates: List[float]


class Bounds(BaseModel):
    type: str
    _id: str
    coordinates: List[List[List[float]]]


class GeoLocation(BaseModel):
    center: Center
    bounds: Optional[Bounds] = None


class Country(BaseModel):
    countryCode: str
    location: Location
    geoLocation: GeoLocation
    registrationNumber: str
    status: str
    createdAt: Optional[str] = None


class Plusimpact(BaseModel):
    status: str


class Views(BaseModel):
    week: int
    total: int


class Doc(BaseModel):
    id: str
    key: str
    name: str
    logoImage: LogoImage
    whatWeDo: str
    website: str
    numberOfEmployees: str
    founded: str
    perks: List[str]
    stage: Optional[str] = None
    funding: str
    fundingStage: Optional[str] = None
    numberOfActiveJobs: int
    createdAt: str
    isImpact: bool
    platform: Platform
    wasRecommended: bool
    recommendedBy: RecommendedBy
    slackNotifications: SlackNotifications
    externalDomain: Optional[str] = None
    sdgs: List[str]
    industries: List[str]
    businessModels: List[str]
    countries: List[Country]
    followed: bool
    unbounceGroup: int
    plusimpact: Plusimpact
    views: Views
    slack: bool
    video: Optional[str] = None
    market: Optional[str] = None


class Countries(BaseModel):
    dk: int
    se: int
    no: int
    fi: int
    ni: int


class Industries(BaseModel):
    consumergoods: int
    education: int
    greentech: int
    entertainment: int
    fintech: int
    healthcare: int
    itsoftware: int
    maritime: int
    saas: int
    service: int
    marketplace: int
    manufacturing: int
    telecommunications: int
    retail: int
    agriculture: int
    food: int
    science: int
    travel: int
    sports: int
    advertising: int
    sales: int
    fashion: int
    hospitality: int
    robotics: int
    legal: int
    jobs: int
    gaming: int
    iot: int
    music: int
    blockchain: int


class Stages(BaseModel):
    growth: int
    idea: int
    goToMarket: int
    prototype: int


class NumberOfEmployees(BaseModel):
    field_51_100: int = Field(..., alias='51-100')
    field_11_50: int = Field(..., alias='11-50')
    field_101_200: int = Field(..., alias='101-200')
    field_1_10: int = Field(..., alias='1-10')
    field_200_: int = Field(..., alias='200+')


class Funding(BaseModel):
    notLooking: int
    funded: int
    looking: int


class Impact(BaseModel):
    true: int
    false: int


class FundingStage(BaseModel):
    seed: int
    seriesa: int
    ipo: int
    preseed: int
    bootstrapping: int
    seriesb: int


class Market(BaseModel):
    both: int
    developed: int
    emerging: int


class Sdgs(BaseModel):
    noPoverty: int
    zeroHunger: int
    goodHealth: int
    qualityEducation: int
    genderEquality: int
    cleanWater: int
    cleanEnergy: int
    economicGrowth: int
    industry: int
    reducedInequalities: int
    suistainableCities: int
    responsibleConsumption: int
    climateAction: int
    lifeBelowWater: int
    lifeOnLand: int
    peace: int
    partnerships: int


class Suggestions(BaseModel):
    countries: Countries
    industries: Industries
    stages: Stages
    numberOfEmployees: NumberOfEmployees
    funding: Funding
    impact: Impact
    fundingStage: FundingStage
    market: Market
    sdgs: Sdgs


class Model(BaseModel):
    docs: Optional[List[Doc]] = None
    total: Optional[int] = None
    limit: Optional[int] = None
    page: Optional[str] = None
    pages: Optional[int] = None
    suggestions: Optional[Suggestions] = None

In [4]:
df.head()

,id,key,name,logoImage,whatWeDo,website,numberOfEmployees,founded,perks,stage,...,industries,businessModels,countries,followed,unbounceGroup,plusimpact,views,slack,video,market
0,61e598bb14c6ea15c0e0c3ad,serverpod,Serverpod,"{'id': '61f2b5ca866d71bf4e840fa2', 'size': 287...",Serverpod is the missing server for the rapidl...,https://serverpod.dev,1-10,2021,"[566563ca872626876801fd1e, 566566ac87262687680...",prototype,...,"[itsoftware, saas, science]",[companies],"[{'countryCode': 'SE', 'location': {'address':...",False,1,{'status': 'DISABLED'},"{'week': 511, 'total': 7747}",False,NaN,NaN
1,5e96e4430aa31106876b43dd,droppe,Droppe â€“ One-stop shop for all your wholesale,"{'id': '624d4a090f29f834380fa175', 'size': 352...",Connecting local businesses to Europe's top eq...,https://droppe.com/company/en,11-50,2020,"[566566ac872626876801fd23, 5d7e475198dc732d926...",growth,...,"[itsoftware, marketplace, sales]",[marketplace],"[{'countryCode': 'SE', 'location': {'address':...",False,1,{'status': 'ACTIVE'},"{'week': 299, 'total': 9874}",False,,both
2,58ca8d506dbf85ee7fc3cf2a,lenus-ehealth,Lenus,"{'id': '633449bf60ad5faa537bf221', 'size': 379...",The health coaching revolution starts here\nLe...,http://lenus.io,200+,2016,"[56656510872626876801fd1f, 566578c087262687680...",growth,...,"[healthcare, itsoftware, saas]",[companies],"[{'countryCode': 'DK', 'location': {'address':...",False,2,{'status': 'DISABLED'},"{'week': 270, 'total': 5848}",False,,NaN
3,5d08acea712bc71c4669a8d1,leetify,Leetify,"{'id': '5d7e39e44def6f3754b733f3', 'size': 293...",Leetify is a software platform that automatica...,https://leetify.com/,1-10,2019,"[566563ca872626876801fd1e, 566565af87262687680...",goToMarket,...,[saas],[consumer],"[{'countryCode': 'SE', 'location': {'address':...",False,1,{'status': 'DISABLED'},"{'week': 212, 'total': 3762}",False,NaN,NaN
4,57b5823d669d8a4d2f94bd56,gomore,GoMore,"{'id': '5d7e47305ea99e161ad2eaf8', 'size': 394...",GoMore is on a mission to help people share ca...,http://www.gomore.dk,51-100,2005,"[56656510872626876801fd1f, 5665653e87262687680...",growth,...,"[itsoftware, service]","[consumer, companies]","[{'countryCode': 'DK', 'location': {'address':...",False,2,{'status': 'ACTIVE'},"{'week': 189, 'total': 5004}",False,,NaN

In [23]:
df.loc[:, ("industries", "businessModels")]

                            industries         businessModels
0          [itsoftware, saas, science]            [companies]
1     [itsoftware, marketplace, sales]          [marketplace]
2       [healthcare, itsoftware, saas]            [companies]
3                               [saas]             [consumer]
4                [itsoftware, service]  [consumer, companies]
...                                ...                    ...
2377      [entertainment, advertising]            [companies]
2378  [marketplace, agriculture, food]          [marketplace]
2379                          [travel]          [marketplace]
2380                   [consumergoods]                     []
2381             [fintech, itsoftware]                     []

[2382 rows x 2 columns]

In [27]:
df.loc[:, ("industries", "businessModels")].replace("[", inplace=True).replace("]", "", inplace=True) 
# replace the [ and ] with nothing in the columsn industries and businessModels and handle the warning of None-Type object has no attribute replace:
df.loc[:, ("industries", "businessModels")] = df.loc[:, ("industries", "businessModels")].str.replace("[", "").str.replace("]", "")

#df.loc[:, ("industries", "businessModels")] = df.loc[:, ("industries", "businessModels")].str.replace("[", "").str.replace("]", "")

AttributeError: 'NoneType' object has no attribute 'replace'

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2382 entries, 0 to 2381
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  2382 non-null   object
 1   key                 2382 non-null   object
 2   name                2382 non-null   object
 3   logoImage           2382 non-null   object
 4   whatWeDo            2382 non-null   object
 5   website             2382 non-null   object
 6   numberOfEmployees   2381 non-null   object
 7   founded             2381 non-null   object
 8   perks               2382 non-null   object
 9   stage               2116 non-null   object
 10  funding             2221 non-null   object
 11  fundingStage        1274 non-null   object
 12  numberOfActiveJobs  2382 non-null   int64
 13  createdAt           2382 non-null   object
 14  isImpact            2382 non-null   bool
 15  platform            2382 non-null   object
 16  wasRecommended      2382 non-null   bool
 17  recommendedBy       2382 non-null   object
 18  slackNotifications  2382 non-null   object
 19  externalDomain      10 non-null     object
 20  sdgs                2382 non-null   object
 21  industries          2382 non-null   object
 22  businessModels      2382 non-null   object
 23  countries           2382 non-null   object
 24  followed            2382 non-null   bool
 25  unbounceGroup       2382 non-null   int64
 26  plusimpact          2382 non-null   object
 27  views               2382 non-null   object
 28  slack               2382 non-null   bool
 29  video               342 non-null    object
 30  market              59 non-null     object
dtypes: bool(4), int64(2), object(25)
memory usage: 511.9+ KB

id                       0
key                      0
name                     0
logoImage                0
whatWeDo                 0
website                  0
numberOfEmployees        1
founded                  1
perks                    0
stage                  266
funding                161
fundingStage          1108
numberOfActiveJobs       0
createdAt                0
isImpact                 0
platform                 0
wasRecommended           0
recommendedBy            0
slackNotifications       0
externalDomain        2372
sdgs                     0
industries               0
businessModels           0
countries                0
followed                 0
unbounceGroup            0
plusimpact               0
views                    0
slack                    0
video                 2040
market                2323
dtype: int64

In [ ]:

import sqlite3

#create a function to import the dtaa into a sqlite database 
def import_data():
    #create a connection to the database
    conn = sqlite3.connect('companies.db')
    #create a cursor
    c = conn.cursor()
    #create a table
    c.execute("""CREATE TABLE IF NOT EXISTS companies (
            id INTEGER PRIMARY KEY,
            name TEXT,
            logo TEXT,
            url TEXT,
            description TEXT,
            country TEXT,
            city TEXT,
            postal_code TEXT,
            address TEXT,
            created_at TEXT,
            updated_at TEXT,
            founded TEXT,
            company_type TEXT,
            company_size TEXT,
            operating_status TEXT,
            last_funding_type TEXT,
            industries TEXT,
            number_of_employees TEXT,
            contact_email TEXT,
            phone_number TEXT,
            facebook_url TEXT,
            twitter_url TEXT,
            linkedin_url TEXT,
            latest_funding_date TEXT,
            latest_funding_amount TEXT,
            latest_funding_round TEXT,
            number_of_investments TEXT,
            number_of_lead_investments TEXT,
            number_of_investors TEXT,
            total_funding_amount TEXT,
            number_of_events TEXT,
            cb_url TEXT,
            cb_uuid TEXT,
            cb_rank TEXT,
            cb_last_funding_at TEXT,
            cb_last_funding_amount TEXT,
            cb_last_funding_type TEXT,
            cb_num_funding_rounds TEXT,
            cb_total_funding_amount TEXT,
            cb_stock_symbol TEXT,
            cb_number_of_investments TEXT,
            cb_number_of_lead_investments TEXT,
            cb_number_of_investors TEXT,
            cb_number_of_acquisitions TEXT,
            cb_acquisition_amount TEXT,
            cb_number_of_board_member_and_advisor_profiles TEXT,
            cb_number_of_current_team_members TEXT,
            cb_number_of_funding_rounds TEXT,
            cb_funding_rounds TEXT,
            cb_funding_types TEXT,
            cb_number_of_investments_per_funding_round TEXT,
            cb_number_of_lead_investors_per_funding_round TEXT,
            cb_number_of_investors_per_funding_round TEXT,
            cb_number_of_unique_investors_per_funding_round TEXT,
            cb_number_of_acquisitions TEXT,
            cb_acquisitions TEXT,
            cb_number_of_diversity_investments TEXT,
            cb_diversity_investments TEXT,
            cb_number_of_diversity_investors TEXT,
            cb_diversity_investors TEXT,
            cb_number_of_exits TEXT,
            cb_exits TEXT,
            cb_number
            )""")
    #import the data from the json file
    with open('results.json', 'r') as f:
        dr = csv.DictReader(f)
        to_db = [(i['id'], i['name'], i['logo'], i['url'], i['description'], i['country'], i['city'], i['postal_code'], i['address'], i['created_at'], i['updated_at'], i['founded'], i['company_type'], i['company_size'], i['operating_status'], i['last_funding_type'], i['industries'], i['number_of_employees'], i['contact_email'], i['phone_number'], i['facebook_url'], i['twitter_url'], i['linkedin_url'], i['latest_funding_date'], i['latest_funding_amount'], i['latest_funding_round'], i['number_of_investments'], i['number_of_lead_investments'], i['number_of_investors'], i['total_funding_amount'], i['number_of_events'], i['cb_url'], i['cb_uuid'], i['cb_rank'], i['cb_last_funding_at'], i['cb_last_funding_amount'], i['cb_last_funding_type'], i['cb_num_funding_rounds'], i['cb_total_funding_amount'], i['cb_stock_symbol'], i['cb_number_of_investments'], i['cb_number_of_lead_investments'], i['cb_number_of_investors'], i['cb_number_of_acquisitions'], i['cb_acquisition_amount'], i['cb_number_of_board_member_and_advisor_profiles'], i['cb_number_of_current_team_members'], i['cb_number_of_funding_rounds'], i['cb_funding_rounds'], i['cb_funding_types'], i['cb_number_of_investments_per_funding_round'], i['cb_number_of_lead_investors_per_funding_round'], i['cb_number_of_investors_per_funding_round'], i['cb_number_of_unique_investors_per_funding_round'], i['cb_number_of_acquisitions'], i['cb_acquisitions'], i['cb_number_of_diversity_investments'], i['cb_diversity_investments'], i['cb_number_of_diversity_investors'], i['cb_diversity_investors'], i['cb_number_of_exits'], i['cb_exits'], i['cb_number']) for i in dr]
        
    #insert the data into the table
    c.executemany("""INSERT INTO companies (
            id,
            name,
            logo,
            url,
            description,
            country,
            city,
            postal_code,
            address,
            created_at,
            updated_at,
            founded,
            company_type,
            company_size,
            operating_status,
            last_funding_type,
            industries,
            number_of_employees,
            contact_email,
            phone_number,
            facebook_url,
            twitter_url,
            linkedin_url,
            latest_funding_date,
            latest_funding_amount,
            latest_funding_round,
            number_of_investments,
            number_of_lead_investments,
            number_of_investors,
            total_funding_amount,
            number_of_events,
            cb_url,
            cb_uuid,
            cb_rank,
            cb_last_funding_at,
            cb_last_funding_amount,
            cb_last_funding_type,
            cb_num_funding_rounds,
            cb_total_funding_amount,
            cb_stock_symbol,
            cb_number_of_investments,
            cb_number_of_lead_investments,
            cb_number_of_investors,
            cb_number_of_acquisitions,
            cb_acquisition_amount,
            cb_number_of_board_member_and_advisor_profiles,
            cb_number_of_current_team_members,
            cb_number_of_funding_rounds,
            cb_funding_rounds,
            cb_funding_types,
            cb_number_of_investments_per_funding_round,
            cb_number_of_lead_investors_per_funding_round,
            cb_number_of_investors_per_funding_round,
            cb_number_of_unique_investors_per_funding_round,
            cb_number_of_acquisitions,
            cb_acquisitions,
            cb_number_of_diversity_investments,
            cb_diversity_investments,
            cb_number_of_diversity_investors,
            cb_diversity_investors,
            cb_number_of_exits,
            cb_exits,
            cb_number
            ) VALUES)""", to_db)

    #commit the changes
    conn.commit()

    #close the connection
    conn.close()

#call the function to import data
import_data()   #call the function to import data